twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']

    paths:
        # liens vers votre dossier image
        '%kernel.project_dir%/public': images
when@test:
    twig:
        strict_variables: true
